version: '3.8'

services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prom.yml:/etc/prometheus/prom.yml

  loki:
    build:
      context: ./loki
      dockerfile: dockerfile
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml

  grafana:
    build:
      context: ./grafana
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/prom-datasource.yml:/etc/grafana/provisioning/datasources/prom-datasource.yml
      - ./grafana/loki-datasource.yml:/etc/grafana/provisioning/datasources/loki-datasource.yml