[phases.build]
cmds = ["echo 'Using existing Dockerfile for build'"]

[phases.setup]
cmds = [
  "mkdir -p /etc/prometheus/secrets",
  "if [ -n \"$PROMETHEUS_AUTH_TOKEN\" ]; then echo \"$PROMETHEUS_AUTH_TOKEN\" > /etc/prometheus/secrets/token && chmod 600 /etc/prometheus/secrets/token && chown 65534:65534 /etc/prometheus/secrets/token; else touch /etc/prometheus/secrets/token; fi"
]

[phases.start]
cmd = "prometheus --config.file=/etc/prometheus/prom.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.enable-lifecycle --web.listen-address=0.0.0.0:$PORT"

[variables]
PORT = "9090" 