[phases.build]
cmds = ["echo 'Using existing Dockerfile for build'"]

[phases.start]
cmd = "prometheus --config.file=/etc/prometheus/prom.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.enable-lifecycle --web.listen-address=0.0.0.0:$PORT"

[variables]
PORT = "9090" 